align with forked from
VadimDor/asdf-plugin-template-ext pull request #1
Opened 2024-01-30 19:20 UTC by VadimDor

2024-01-30 19:56 UTC, VadimDor commented
lets merge it

2024-01-31 09:00 UTC, radiocab requested changes
aprove all

2024-01-31 09:00 UTC, radiocab commented on .github/dependabot.yml
> -    directory: "./github"
aprove changes

2024-01-31 09:00 UTC, radiocab commented on template/.github/dependabot.yml
> -    directory: "./github"
approve

2024-01-31 09:01 UTC, radiocab approved these changes

2024-01-31 09:43 UTC, closed without merging